name: Deploy ke VPS Webuzo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil kode terbaru dari GitHub
        uses: actions/checkout@v4

      - name: Upload otomatis ke VPS via SFTP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          source: "."
          target: "/home/${{ secrets.FTP_USERNAME }}/public_html/"